import 'dotenv/config';
import express, {Request, Response, NextFunction} from 'express';
import http from 'http';
import path from 'path';
import fs from 'fs';
import crypto from 'crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import cors from 'cors';
import helmet from 'helmet';
import cookieParser from 'cookie-parser';
import rateLimit from 'express-rate-limit';
import multer from 'multer';
import nodemailer from 'nodemailer';
import {Server as SocketServer} from 'socket.io';
import {PrismaClient, SwipeType, ReportReason, VerificationType, PaymentStatus, SubscriptionStatus, PhotoStatus} from '@prisma/client';

const prisma=new PrismaClient();
const app=express();
const server=http.createServer(app);
const io=new SocketServer(server,{cors:{origin:process.env.FRONTEND_URL||'*',credentials:true}});
const PORT=Number(process.env.PORT||4000);
const JWT_SECRET=process.env.JWT_SECRET||'dev-only-secret';
const REFRESH_SECRET=process.env.JWT_REFRESH_SECRET||'dev-only-refresh';
const uploadDir=path.resolve(process.env.UPLOAD_DIR||'./data/uploads');fs.mkdirSync(uploadDir,{recursive:true});

app.use(helmet({crossOriginResourcePolicy:{policy:'cross-origin'}}));
app.use(cors({origin:process.env.FRONTEND_URL||'http://localhost:4000',credentials:true}));
app.use(express.json({limit:'2mb'}));app.use(cookieParser());
app.use('/uploads',express.static(uploadDir));
app.use(express.static(path.resolve(process.cwd(),'public')));
app.get('/admin',(req,res)=>res.sendFile(path.resolve(process.cwd(),'public/admin.html')));
app.use(rateLimit({windowMs:15*60*1000,max:500,standardHeaders:true,legacyHeaders:false}));

const upload=multer({dest:uploadDir,limits:{fileSize:Number(process.env.MAX_UPLOAD_MB||8)*1024*1024},fileFilter:(_r,file,cb)=>cb(null,['image/jpeg','image/png','image/webp'].includes(file.mimetype))});

type AuthedRequest=Request & {user?:any};
const asyncRoute=(fn:any)=>(req:Request,res:Response,next:NextFunction)=>Promise.resolve(fn(req,res,next)).catch(next);
function signAccess(user:any){return jwt.sign({sub:user.id,role:user.role},JWT_SECRET,{expiresIn:'15m'});}
function signRefresh(user:any){return jwt.sign({sub:user.id},REFRESH_SECRET,{expiresIn:'30d'});}
async function auth(req:AuthedRequest,res:Response,next:NextFunction){try{const h=req.headers.authorization;if(!h?.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});const p=jwt.verify(h.slice(7),JWT_SECRET) as any;const user=await prisma.user.findUnique({where:{id:p.sub}});if(!user||user.status!=='ACTIVE')return res.status(401).json({error:'Account unavailable'});req.user=user;next()}catch{return res.status(401).json({error:'Invalid or expired token'})}}
function requireRole(...roles:string[]){return (req:AuthedRequest,res:Response,next:NextFunction)=>roles.includes(req.user?.role)?next():res.status(403).json({error:'Forbidden'})}
function randomCode(){return String(crypto.randomInt(100000,999999));}
function hash(v:string){return crypto.createHash('sha256').update(v).digest('hex');}
function publicUser(u:any){return {id:u.id,firstName:u.firstName,lastName:u.lastName,dateOfBirth:u.dateOfBirth,gender:u.gender,interestedIn:u.interestedIn,bio:u.bio,city:u.city,country:u.country,relationshipGoal:u.relationshipGoal,languages:u.languages,interests:u.interests,emailVerified:u.emailVerified,phoneVerified:u.phoneVerified,photoVerified:u.photoVerified,photos:u.photos?.filter((p:any)=>p.status==='APPROVED').map((p:any)=>({id:p.id,url:p.url,isPrimary:p.isPrimary}))||[]}}

const mailer=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:Number(process.env.SMTP_PORT||587)===465,auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}}):null;
async function sendEmail(to:string,subject:string,text:string){if(!mailer){console.log(`[EMAIL DEV] ${to} ${subject}: ${text}`);return;}await mailer.sendMail({from:process.env.MAIL_FROM,to,subject,text});}
async function sendSms(to:string,body:string){
  const sid=process.env.TWILIO_VERIFY_SERVICE_SID;
  if(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!sid){console.log(`[SMS DEV] ${to}: ${body}`);return;}
  const basic=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64');
  const params=new URLSearchParams({To:to,Channel:'sms'});
  await fetch(`https://verify.twilio.com/v2/Services/${sid}/Verifications`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:params});
}
async function verifySmsCode(to:string,code:string){
  const sid=process.env.TWILIO_VERIFY_SERVICE_SID;
  if(!process.env.TWILIO_ACCOUNT_SID||!process.env.TWILIO_AUTH_TOKEN||!sid)return false;
  const basic=Buffer.from(`${process.env.TWILIO_ACCOUNT_SID}:${process.env.TWILIO_AUTH_TOKEN}`).toString('base64');
  const params=new URLSearchParams({To:to,Code:code});
  const r=await fetch(`https://verify.twilio.com/v2/Services/${sid}/VerificationCheck`,{method:'POST',headers:{Authorization:`Basic ${basic}`,'Content-Type':'application/x-www-form-urlencoded'},body:params});
  const data:any=await r.json();return r.ok&&data.status==='approved';
}
const intaBase=process.env.INTASEND_TEST==='true'?'https://sandbox.intasend.com':'https://api.intasend.com';
async function inta(pathname:string,method='POST',body?:any){const key=process.env.INTASEND_SECRET_KEY;if(!key)throw new Error('IntaSend secret key not configured');const r=await fetch(`${intaBase}${pathname}`,{method,headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json',Accept:'application/json'},body:body?JSON.stringify(body):undefined});const text=await r.text();let data:any;try{data=JSON.parse(text)}catch{data={raw:text}}if(!r.ok)throw new Error(`IntaSend ${r.status}: ${text}`);return data;}

app.get('/health',(_req,res)=>res.json({ok:true,service:'motinder-backend',time:new Date().toISOString()}));

app.post('/api/auth/register',asyncRoute(async(req,res)=>{
 const s=express.json; const body=req.body||{}; const email=String(body.email||'').trim().toLowerCase();const password=String(body.password||'');
 if(!email||password.length<8||!body.firstName||!body.dateOfBirth)return res.status(400).json({error:'firstName, email, dateOfBirth and a password of at least 8 characters are required'});
 const dob=new Date(body.dateOfBirth);const age=Math.floor((Date.now()-dob.getTime())/31557600000);if(age<18)return res.status(400).json({error:'Motinder is for adults 18+'});
 if(await prisma.user.findUnique({where:{email}}))return res.status(409).json({error:'Email already registered'});
 const passwordHash=await bcrypt.hash(password,12);const user=await prisma.user.create({data:{email,passwordHash,firstName:String(body.firstName),lastName:body.lastName||null,dateOfBirth:dob,gender:body.gender||null,interestedIn:body.interestedIn||[],country:body.country||'KE',languages:body.languages||[],interests:body.interests||[],relationshipGoal:body.relationshipGoal||null}}); if(body.phone){const phone=String(body.phone).trim();if(!/^\+?[1-9]\d{7,14}$/.test(phone))return res.status(400).json({error:'Use an international phone number'});const taken=await prisma.user.findFirst({where:{phone}});if(taken){await prisma.user.delete({where:{id:user.id}});return res.status(409).json({error:'Phone number already in use'});}await prisma.user.update({where:{id:user.id},data:{phone}});}
 const code=randomCode();await prisma.verificationCode.create({data:{userId:user.id,type:'EMAIL',target:email,codeHash:hash(code),expiresAt:new Date(Date.now()+10*60*1000)}});await sendEmail(email,'Verify your Motinder email',`Your Motinder verification code is ${code}. It expires in 10 minutes.`);
 const access=signAccess(user),refresh=signRefresh(user);await prisma.refreshToken.create({data:{userId:user.id,tokenHash:hash(refresh),expiresAt:new Date(Date.now()+30*86400000)}});res.cookie('motinder_refresh',refresh,{httpOnly:true,secure:process.env.COOKIE_SECURE==='true',sameSite:'lax',maxAge:30*86400000});res.status(201).json({accessToken:access,user:publicUser(user),requiresEmailVerification:true});
}));
app.post('/api/auth/login',asyncRoute(async(req,res)=>{const email=String(req.body.email||'').toLowerCase(),password=String(req.body.password||'');const user=await prisma.user.findUnique({where:{email},include:{photos:true}});if(!user||!(await bcrypt.compare(password,user.passwordHash)))return res.status(401).json({error:'Invalid email or password'});if(user.status!=='ACTIVE')return res.status(403).json({error:'Account is not active'});await prisma.user.update({where:{id:user.id},data:{lastActiveAt:new Date()}});const refresh=signRefresh(user);await prisma.refreshToken.create({data:{userId:user.id,tokenHash:hash(refresh),expiresAt:new Date(Date.now()+30*86400000)}});res.cookie('motinder_refresh',refresh,{httpOnly:true,secure:process.env.COOKIE_SECURE==='true',sameSite:'lax',maxAge:30*86400000});res.json({accessToken:signAccess(user),user:publicUser(user)});}));
app.post('/api/auth/refresh',asyncRoute(async(req,res)=>{const token=req.cookies.motinder_refresh;if(!token)return res.status(401).json({error:'No refresh token'});const p=jwt.verify(token,REFRESH_SECRET) as any;const row=await prisma.refreshToken.findFirst({where:{userId:p.sub,tokenHash:hash(token),revokedAt:null,expiresAt:{gt:new Date()}}});if(!row)return res.status(401).json({error:'Refresh token invalid'});const user=await prisma.user.findUnique({where:{id:p.sub}});if(!user)return res.status(401).json({error:'Account not found'});res.json({accessToken:signAccess(user)});}));
app.post('/api/auth/logout',asyncRoute(async(req,res)=>{const token=req.cookies.motinder_refresh;if(token)await prisma.refreshToken.updateMany({where:{tokenHash:hash(token)},data:{revokedAt:new Date()}});res.clearCookie('motinder_refresh');res.json({ok:true});}));

app.post('/api/auth/send-verification',auth,asyncRoute(async(req:AuthedRequest,res)=>{const type=req.body.type==='PHONE'?'PHONE':'EMAIL';const target=type==='PHONE'?req.user.phone:req.user.email;if(!target)return res.status(400).json({error:type==='PHONE'?'Add a phone number first':'Email is missing'});if(type==='PHONE'&&process.env.TWILIO_VERIFY_SERVICE_SID){await sendSms(target,'');res.json({ok:true});return;}const code=randomCode();await prisma.verificationCode.create({data:{userId:req.user.id,type,target,codeHash:hash(code),expiresAt:new Date(Date.now()+10*60*1000)}});type==='PHONE'?await sendSms(target,`Your Motinder verification code is ${code}. It expires in 10 minutes.`):await sendEmail(target,'Your Motinder verification code',`Your Motinder verification code is ${code}. It expires in 10 minutes.`);res.json({ok:true});}));
app.post('/api/auth/verify',auth,asyncRoute(async(req:AuthedRequest,res)=>{const type=req.body.type==='PHONE'?'PHONE':'EMAIL';const code=String(req.body.code||'');if(type==='PHONE'&&process.env.TWILIO_VERIFY_SERVICE_SID){const ok=await verifySmsCode(req.user.phone,code);if(!ok)return res.status(400).json({error:'Invalid or expired verification code'});}else{const row=await prisma.verificationCode.findFirst({where:{userId:req.user.id,type,status:'PENDING',expiresAt:{gt:new Date()}},orderBy:{createdAt:'desc'}});if(!row||row.codeHash!==hash(code))return res.status(400).json({error:'Invalid or expired verification code'});await prisma.verificationCode.update({where:{id:row.id},data:{status:'VERIFIED'}});}const data=type==='PHONE'?{phoneVerified:true}:{emailVerified:true};const user=await prisma.user.update({where:{id:req.user.id},data,include:{photos:true}});res.json({user:publicUser(user)});}));
app.put('/api/account/phone',auth,asyncRoute(async(req:AuthedRequest,res)=>{const phone=String(req.body.phone||'').trim();if(!/^\+?[1-9]\d{7,14}$/.test(phone))return res.status(400).json({error:'Use an international phone number'});const exists=await prisma.user.findFirst({where:{phone,id:{not:req.user.id}}});if(exists)return res.status(409).json({error:'Phone number already in use'});const user=await prisma.user.update({where:{id:req.user.id},data:{phone,phoneVerified:false}});res.json({user:publicUser(user),requiresPhoneVerification:true});}));
app.put('/api/profile',auth,asyncRoute(async(req:AuthedRequest,res)=>{const allowed=['firstName','lastName','gender','interestedIn','bio','city','country','relationshipGoal','languages','interests','incognito','discoverable'];const data:any={};for(const k of allowed)if(req.body[k]!==undefined)data[k]=req.body[k];const user=await prisma.user.update({where:{id:req.user.id},data,include:{photos:true}});res.json({user:publicUser(user)});}));
app.post('/api/location',auth,asyncRoute(async(req:AuthedRequest,res)=>{const lat=Number(req.body.latitude),lon=Number(req.body.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon)||lat<-90||lat>90||lon<-180||lon>180)return res.status(400).json({error:'Invalid coordinates'});await prisma.user.update({where:{id:req.user.id},data:{latitude:lat,longitude:lon,locationUpdatedAt:new Date()}});res.json({ok:true});}));

app.get('/api/discover',auth,asyncRoute(async(req:AuthedRequest,res)=>{const distance=Number(req.query.distance||50);const maxAge=Number(req.query.maxAge||80),minAge=Number(req.query.minAge||18);const users=await prisma.user.findMany({where:{id:{not:req.user.id},status:'ACTIVE',discoverable:true,dateOfBirth:{lte:new Date(Date.now()-minAge*31557600000),gte:new Date(Date.now()-maxAge*31557600000)},emailVerified:true,photos:{some:{status:'APPROVED'}}},include:{photos:true},take:200});const swipes=await prisma.swipe.findMany({where:{fromUserId:req.user.id}});const seen=new Set(swipes.map(s=>s.toUserId));const result=users.filter(u=>!seen.has(u.id)).filter(u=>{if(req.user.latitude==null||req.user.longitude==null||u.latitude==null||u.longitude==null)return true;const d=haversine(req.user.latitude,req.user.longitude,u.latitude,u.longitude);return d<=distance}).sort((a,b)=>score(req.user,a)-score(req.user,b));res.json({profiles:result.slice(0,50).map(publicUser)});}));
function haversine(a:number,b:number,c:number,d:number){const R=6371,rad=Math.PI/180;const x=(c-a)*rad,y=(d-b)*rad;const h=Math.sin(x/2)**2+Math.cos(a*rad)*Math.cos(c*rad)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(h));}
function score(me:any,u:any){let s=0;s+=u.interests?.filter((x:string)=>me.interests?.includes(x)).length*10||0;s+=u.relationshipGoal&&u.relationshipGoal===me.relationshipGoal?20:0;s+=u.photoVerified?10:0;if(me.latitude&&me.longitude&&u.latitude&&u.longitude)s+=Math.max(0,20-haversine(me.latitude,me.longitude,u.latitude,u.longitude));return -s;}
app.post('/api/swipes',auth,asyncRoute(async(req:AuthedRequest,res)=>{const to=String(req.body.toUserId),type=req.body.type as SwipeType;if(req.user.id===to||!['LIKE','PASS','SUPERLIKE'].includes(type))return res.status(400).json({error:'Invalid swipe'});const target=await prisma.user.findUnique({where:{id:to}});if(!target)return res.status(404).json({error:'User not found'});const swipe=await prisma.swipe.upsert({where:{fromUserId_toUserId:{fromUserId:req.user.id,toUserId:to}},update:{type},create:{fromUserId:req.user.id,toUserId:to,type}});let match=null;if(type!=='PASS'){const reciprocal=await prisma.swipe.findUnique({where:{fromUserId_toUserId:{fromUserId:to,toUserId:req.user.id}}});if(reciprocal&&['LIKE','SUPERLIKE'].includes(reciprocal.type)){const [a,b]=req.user.id<to?[req.user.id,to]:[to,req.user.id];match=await prisma.match.upsert({where:{userAId_userBId:{userAId:a,userBId:b}},update:{status:'ACTIVE'},create:{userAId:a,userBId:b}});await notify(to,'New match ✨',`${req.user.firstName} matched with you!`,'MATCH',{matchId:match.id});}}
res.json({swipe,match});}));

app.get('/api/likes',auth,asyncRoute(async(req:AuthedRequest,res)=>{const rows=await prisma.swipe.findMany({where:{toUserId:req.user.id,type:{in:['LIKE','SUPERLIKE']}},include:{fromUser:{include:{photos:true}}},orderBy:{createdAt:'desc'},take:100});res.json({likes:rows.map(x=>publicUser(x.fromUser))});}));

app.get('/api/matches',auth,asyncRoute(async(req:AuthedRequest,res)=>{const rows=await prisma.match.findMany({where:{status:'ACTIVE',OR:[{userAId:req.user.id},{userBId:req.user.id}]},include:{userA:{include:{photos:true}},userB:{include:{photos:true}}},orderBy:{updatedAt:'desc'}});res.json({matches:rows.map(m=>({id:m.id,user:publicUser(m.userAId===req.user.id?m.userB:m.userA)}))});}));
app.post('/api/matches/:id/unmatch',auth,asyncRoute(async(req:AuthedRequest,res)=>{const m=await prisma.match.findUnique({where:{id:req.params.id}});if(!m||![m.userAId,m.userBId].includes(req.user.id))return res.status(404).json({error:'Match not found'});await prisma.match.update({where:{id:m.id},data:{status:'UNMATCHED'}});res.json({ok:true});}));

app.get('/api/matches/:id/messages',auth,asyncRoute(async(req:AuthedRequest,res)=>{const m=await prisma.match.findUnique({where:{id:req.params.id}});if(!m||![m.userAId,m.userBId].includes(req.user.id))return res.status(404).json({error:'Match not found'});const messages=await prisma.message.findMany({where:{matchId:m.id},orderBy:{createdAt:'asc'},take:100});res.json({messages});}));
app.post('/api/matches/:id/messages',auth,asyncRoute(async(req:AuthedRequest,res)=>{const m=await prisma.match.findUnique({where:{id:req.params.id}});if(!m||m.status!=='ACTIVE'||![m.userAId,m.userBId].includes(req.user.id))return res.status(404).json({error:'Match not found'});const body=String(req.body.body||'').trim();if(!body||body.length>4000)return res.status(400).json({error:'Message must be 1-4000 characters'});const msg=await prisma.message.create({data:{matchId:m.id,senderId:req.user.id,body}});io.to(`match:${m.id}`).emit('message:new',msg);const recipient=m.userAId===req.user.id?m.userBId:m.userAId;await notify(recipient,req.user.firstName,body,'MESSAGE',{matchId:m.id,messageId:msg.id});res.status(201).json(msg);}));

app.post('/api/devices',auth,asyncRoute(async(req:AuthedRequest,res)=>{const token=String(req.body.token||'');const platform=String(req.body.platform||'web');if(!token)return res.status(400).json({error:'token required'});const device=await prisma.device.upsert({where:{token},update:{userId:req.user.id,platform},create:{userId:req.user.id,token,platform}});res.json(device);}));
async function notify(userId:string,title:string,body:string,type:string,data:any={}){const n=await prisma.notification.create({data:{userId,title,body,type,data}});const devices=await prisma.device.findMany({where:{userId}});if(process.env.FIREBASE_PROJECT_ID&&devices.length){try{const admin=(await import('firebase-admin')).default;if(!admin.apps.length){admin.initializeApp({credential:admin.credential.cert({projectId:process.env.FIREBASE_PROJECT_ID,clientEmail:process.env.FIREBASE_CLIENT_EMAIL,privateKey:(process.env.FIREBASE_PRIVATE_KEY||'').replace(/\n/g,'\n')})})}await admin.messaging().sendEachForMulticast({tokens:devices.map(d=>d.token),notification:{title,body},data:Object.fromEntries(Object.entries(data).map(([k,v])=>[k,String(v)]))});}catch(e){console.error('Push error',e)}}if(process.env.SMTP_HOST){const u=await prisma.user.findUnique({where:{id:userId},select:{email:true}});if(u?.email)sendEmail(u.email,title,body).catch(console.error)}return n;}

app.post('/api/photos',auth,upload.single('photo'),asyncRoute(async(req:AuthedRequest,res)=>{if(!req.file)return res.status(400).json({error:'Photo required'});const url=`/uploads/${path.basename(req.file.path)}`;const primary=(await prisma.photo.count({where:{userId:req.user.id,status:'APPROVED'}}))===0;const photo=await prisma.photo.create({data:{userId:req.user.id,url,storageKey:req.file.filename,isPrimary:primary,status:'PENDING'}});await moderatePhoto(photo.id);res.status(201).json(photo);}));
async function moderatePhoto(photoId:string){const photo=await prisma.photo.findUnique({where:{id:photoId}});if(!photo)return;/* Production hook: send the file to an image-safety provider here. Default is human/admin review. */await prisma.photo.update({where:{id:photoId},data:{status:'PENDING',moderationNote:'Awaiting moderation'}});}

app.post('/api/users/:id/block',auth,asyncRoute(async(req:AuthedRequest,res)=>{const target=await prisma.user.findUnique({where:{id:req.params.id}});if(!target||target.id===req.user.id)return res.status(404).json({error:'User not found'});await prisma.swipe.upsert({where:{fromUserId_toUserId:{fromUserId:req.user.id,toUserId:target.id}},update:{type:'PASS'},create:{fromUserId:req.user.id,toUserId:target.id,type:'PASS'}});res.json({ok:true});}));
app.post('/api/reports',auth,asyncRoute(async(req:AuthedRequest,res)=>{const reportedId=String(req.body.reportedId),reason=req.body.reason as ReportReason;if(reportedId===req.user.id||!Object.values(ReportReason).includes(reason))return res.status(400).json({error:'Invalid report'});const report=await prisma.report.create({data:{reporterId:req.user.id,reportedId,reason,details:req.body.details||null}});res.status(201).json(report);}));

app.get('/api/admin/stats',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(_req,res)=>{const [users,active,openReports,pendingPhotos,subscriptions]=await Promise.all([prisma.user.count(),prisma.user.count({where:{status:'ACTIVE'}}),prisma.report.count({where:{status:'OPEN'}}),prisma.photo.count({where:{status:'PENDING'}}),prisma.subscription.count({where:{status:'ACTIVE'}})]);res.json({users,active,openReports,pendingPhotos,activeSubscriptions:subscriptions});}));
app.get('/api/admin/reports',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(req,res)=>{const rows=await prisma.report.findMany({where:{status:req.query.status as any||'OPEN'},include:{reporter:true,reported:true},orderBy:{createdAt:'desc'},take:100});res.json(rows.map(r=>({...r,reporter:publicUser(r.reporter),reported:publicUser(r.reported)})));}));
app.post('/api/admin/reports/:id/resolve',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(req:AuthedRequest,res)=>{const status=req.body.action==='dismiss'?'DISMISSED':'RESOLVED';const report=await prisma.report.update({where:{id:req.params.id},data:{status,resolution:String(req.body.resolution||''),moderatorId:req.user.id}});if(req.body.action==='ban')await prisma.user.update({where:{id:report.reportedId},data:{status:'BANNED',discoverable:false}});await prisma.adminAuditLog.create({data:{adminId:req.user.id,action:req.body.action||'resolve',targetType:'REPORT',targetId:report.id,metadata:req.body}});res.json(report);}));
app.get('/api/admin/users',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(req,res)=>{const rows=await prisma.user.findMany({include:{photos:true},orderBy:{createdAt:'desc'},take:100});res.json(rows.map(publicUser));}));
app.get('/api/admin/photos',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(_req,res)=>{const rows=await prisma.photo.findMany({where:{status:'PENDING'},include:{user:true},orderBy:{createdAt:'asc'},take:100});res.json(rows.map(p=>({...p,user:publicUser(p.user)})));}));
app.post('/api/admin/photos/:id/review',auth,requireRole('ADMIN','MODERATOR'),asyncRoute(async(req:AuthedRequest,res)=>{const status=req.body.approved?'APPROVED':'REJECTED';const photo=await prisma.photo.update({where:{id:req.params.id},data:{status,moderationNote:req.body.note||null}});await prisma.adminAuditLog.create({data:{adminId:req.user.id,action:'photo_review',targetType:'PHOTO',targetId:photo.id,metadata:{status}}});res.json(photo);}));

app.get('/api/payments',auth,asyncRoute(async(req:AuthedRequest,res)=>{const rows=await prisma.payment.findMany({where:{userId:req.user.id},orderBy:{createdAt:'desc'},take:50});res.json({payments:rows});}));
app.post('/api/payments/subscribe',auth,asyncRoute(async(req:AuthedRequest,res)=>{const plan=String(req.body.plan||'MONTHLY');const config:any={MONTHLY:{id:process.env.INTASEND_MONTHLY_PLAN_ID},THREE_MONTHS:{id:process.env.INTASEND_3MONTH_PLAN_ID},ANNUAL:{id:process.env.INTASEND_ANNUAL_PLAN_ID}}[plan];if(!config?.id)return res.status(503).json({error:'This IntaSend plan is not configured yet'});let sub=await prisma.subscription.create({data:{userId:req.user.id,plan,status:'PENDING',intasendPlanId:config.id}});let customerId=(await prisma.subscription.findFirst({where:{userId:req.user.id,intasendCustomerId:{not:null}}))?.intasendCustomerId;if(!customerId){const c=await inta('/api/v1/subscriptions-customers/', 'POST',{email:req.user.email,first_name:req.user.firstName,last_name:req.user.lastName||'',reference:req.user.id,country:req.user.country||'KE'});customerId=c.customer_id;sub=await prisma.subscription.update({where:{id:sub.id},data:{intasendCustomerId:customerId}});}const reference=`MOT_${sub.id}`;const result=await inta('/api/v1/subscriptions/','POST',{customer_id:customerId,reference,plan_id:config.id,start_date:new Date().toISOString().slice(0,10),redirect_url:`${process.env.FRONTEND_URL}/payment/success?subscription=${sub.id}`});sub=await prisma.subscription.update({where:{id:sub.id},data:{intasendCustomerId:customerId,intasendSubscriptionId:result.subscription_id}});await prisma.payment.create({data:{userId:req.user.id,subscriptionId:sub.id,reference,amount:0,currency:'KES',status:'PENDING',rawPayload:result}});res.json({subscriptionId:sub.id,setupUrl:result.setup_url});}));
app.post('/api/payments/checkout',auth,asyncRoute(async(req:AuthedRequest,res)=>{const amount=Number(req.body.amount);if(!Number.isFinite(amount)||amount<=0)return res.status(400).json({error:'Invalid amount'});const reference=`MOT_${crypto.randomUUID()}`;const result=await inta('/api/v1/checkout/','POST',{first_name:req.user.firstName,last_name:req.user.lastName||'',phone_number:req.user.phone,email:req.user.email,country:req.user.country||'KE',api_ref:reference,method:req.body.method||'M-PESA',channel:'WEBSITE',host:process.env.APP_URL,redirect_url:`${process.env.FRONTEND_URL}/payment/success?reference=${reference}`,amount:amount.toFixed(2),currency:req.body.currency||'KES'});await prisma.payment.create({data:{userId:req.user.id,reference,invoiceId:result.invoice_id||result.invoice?.invoice_id||null,amount,currency:req.body.currency||'KES',status:'PENDING',rawPayload:result}});res.json({reference,invoiceId:result.invoice_id||result.invoice?.invoice_id,checkoutUrl:result.url||result.checkout_url||result});}));
app.post('/api/payments/refund',auth,asyncRoute(async(req:AuthedRequest,res)=>{const payment=await prisma.payment.findFirst({where:{id:req.body.paymentId,userId:req.user.id}});if(!payment?.invoiceId)return res.status(404).json({error:'Refundable payment not found'});if(!['COMPLETE','PARTIAL_REFUND'].includes(payment.status))return res.status(400).json({error:'Payment is not refundable in its current state'});const amount=Math.min(Number(req.body.amount||payment.amount.toString()),Number(payment.amount));const result=await inta('/api/v1/chargebacks/','POST',{invoice_id:payment.invoiceId,amount:amount.toFixed(2),reason:String(req.body.reason||'Customer refund request')});res.json({ok:true,result});}));
app.post('/api/payments/intasend/webhook',express.json(),asyncRoute(async(req,res)=>{const payload=req.body||{};if(process.env.INTASEND_WEBHOOK_CHALLENGE&&payload.challenge!==process.env.INTASEND_WEBHOOK_CHALLENGE)return res.status(401).json({error:'Invalid webhook challenge'});const reference=payload.api_ref||payload.reference;if(reference){const p=await prisma.payment.findUnique({where:{reference}});if(p){const state=String(payload.state||payload.payment?.state||'').toUpperCase();const status:PaymentStatus=state==='COMPLETE'?'COMPLETE':state==='FAILED'?'FAILED':state==='PROCESSING'?'PROCESSING':'PENDING';await prisma.payment.update({where:{id:p.id},data:{status,invoiceId:payload.invoice_id||p.invoiceId,rawPayload:payload}});if(status==='COMPLETE'&&p.subscriptionId)await prisma.subscription.update({where:{id:p.subscriptionId},data:{status:'ACTIVE',startsAt:new Date()}});await notify(p.userId,'Payment update',`Your Motinder payment is ${status.toLowerCase()}.`,'PAYMENT',{reference,status});}}res.json({received:true});}));

io.use((socket,next)=>{try{const token=socket.handshake.auth?.token;if(!token)return next(new Error('Authentication required'));const p=jwt.verify(token,JWT_SECRET) as any;socket.data.userId=p.sub;next()}catch{next(new Error('Invalid token'))}});
io.on('connection',socket=>{socket.on('match:join',async(matchId:string)=>{const m=await prisma.match.findUnique({where:{id:matchId}});if(m&&[m.userAId,m.userBId].includes(socket.data.userId))socket.join(`match:${matchId}`)});socket.on('typing',(matchId:string)=>socket.to(`match:${matchId}`).emit('typing',{userId:socket.data.userId}));});

app.use((err:any,_req:Request,res:Response,_next:NextFunction)=>{console.error(err);res.status(500).json({error:'Internal server error',detail:process.env.NODE_ENV==='development'?err.message:undefined});});
server.listen(PORT,()=>console.log(`Motinder full stack listening on http://localhost:${PORT}`));
